- name: Allow no password with sudo
  hosts: localhost
  tasks:
    - name: Get the username running the deploy
      become: false
      local_action: command whoami
      register: task_whoami
    
    - debug: 
        var: task_whoami.stdout

    - name: Create {{task_whoami.stdout}} sudoers rule
      become: true
      copy:
        dest: "/etc/sudoers.d/{{task_whoami.stdout}}"
        content: |
          {{task_whoami.stdout}}  ALL=(ALL) NOPASSWD:ALL