- name: Allow no password with sudo
  hosts: localhost
  tasks:
    - name: Get the username running the deploy
      become: false
      local_action: command whoami
      register: target_username.stdout
    
    - debug: 
        var: target_username

    - name: Create {{target_username}} sudoers rule
      become: true
      copy:
        dest: "/etc/sudoers.d/{{target_username}}"
        content: |
          {{target_username}}  ALL=(ALL) NOPASSWD:ALL